### ISSUE TITLE
Does the process_xms() support all version ?

### ISSUE THREAD

**Issue by shevc08** [MikuAuahDark/SIF_Win32#4]
Does the process_xms() support all 5 versions(4.x) ? and if not ,how can i get the hmac_key ?

**Comment by MikuAuahDark** [comment]
XMC (written as `XMS` in SIF-Win32 due to typo) is actually only different for each SIF servers. Example JP and EN XMC is different.

If you'd like to change the XMC, use `-xmc <x message code key>` command-line when starting SIF-Win32.

Sharing the HMAC key is risky because it can be abused, so you need to figure it out yourself.

**Comment by UraKn0x** [comment]
Should the XMC key specified with the -xmc parameter be formatted in base 64?

**Comment by MikuAuahDark** [comment]
No. It must be plaintext. IIRC SIF XMC is always readable characters.

**Comment by UraKn0x** [comment]
Hmmm... the XMC for NPPS is base64(repeat('\0', 128)) though IIRC...

**Comment by MikuAuahDark** [comment]
That's XMS, not XMC.

**Comment by UraKn0x** [comment]
Oh, I guess I've been confused by the XMS/XMC typo here. Okay then, is there a simple way to change the actual XMS in SIF_Win32 or is the XMS check already disabled?

**Comment by Caraxi** [comment]
XMC check is done both server side and client side, so its not disable-able

**Comment by UraKn0x** [comment]
I meant, the actual XMS, to use it with NPPS.

**Comment by Caraxi** [comment]
oh, XMS checking is disabled on SifWin32, yes
